import react from "@/lottie/react.json";
import html from "@/lottie/html.json";
import github from "@/lottie/github.json";
import javaScripts from "@/lottie/javaScripts.json";
import git from "@/lottie/git.json";

const data = (t) => [
  {
    title: "Html",
    animation: html,
    detail: [
      t("HTML5"),
      t("Multimedia"),
      t("Forms"),
      t("Semantic"),
      t("Attributes"),
      t("Graphics"),
      t("Tables"),
      t("link"),
      t("list"),
      t("Frames"),
      t("APIs"),
    ],
  },
  {
    title: "Css",
    logo: true,
    detail: [
      t("Responsive"),
      t("Media"),
      t("Selectors"),
      t("Box"),
      t("Typography"),
      t("Flexbox"),
      t("Grid"),
      t("Positioning"),
      t("Pseudo"),
      t("Variables"),
    ],
  },
  {
    title: "JavaScripts",
    animation: javaScripts,
    detail: [
      t("ES"),
      t("Type"),
      t("Operators"),
      t("Conditional"),
      t("data"),
      t("Dom"),
      t("Bom"),
      t("Acynchronous"),
      t("Error"),
    ],
  },
  {
    title: "React js",
    animation: react,
    detail: [
      t("Jsx"),
      t("class"),
      t("Based"),
      t("Functional"),
      t("LifeCycle"),
      t("hook"),
      t("Context"),
      t("api"),
      t("Validation"),
      t("Prop"),
      t("Material"),
      t("style"),
      t("Module"),
      t("Redux"),
      t("Router"),
      t("Query"),
      t("Devtools"),
    ],
  },
  {
    title: "Next",
    logo: true,
    detail: [
      t("pagef"),
      t("dynamic"),
      t("customf"),
      t("reusable"),
      t("rhandler"),
      t("auth"),
      t("athentication"),
      t("middleware"),
      t("custimmiddle"),
      t("optimization"),
      t("spliting"),
      t("lazy"),
      t("apiroute"),
      t("webpack"),
      t("plugines"),
      t("prouter"),
      t("approuter"),
      t("ssr"),
      t("ppr"),
      t("isr"),
      t("ssg"),
    ],
  },
  {
    title: "TypeScript",
    logo: true,
    detail: [
      t("typesd"),
      t("btypesd"),
      t("complex"),
      t("interfaces"),
      t("Oriented"),
      t("enum"),
      t("generic"),
      t("Annotations"),
      t("import"),
      t("nulll"),
      t("Compilation"),
      t("Testing"),
      t("Intersection"),
      t("andling"),
      t("Frameworks"),
    ],
  },
  {
    title: "PWA",
    logo: true,
    detail: [
      t("Worke"),
      t("Caching"),
      t("App"),
      t("Web"),
      t("Offlin"),
      t("Background"),
      t("Notifications"),
      t("Performance"),
      t("Enhancement"),
      t("Push"),
      t("Security"),
      t("sting"),
      t("loyment"),
      t("SEO"),
      t("Existin"),
    ],
  },
  {
    title: "Git",
    animation: git,
    detail: [
      t("ripo"),
      t("changes"),
      t("branch"),
      t("remote"),
      t("conflicts"),
      t("undo"),
    ],
  },

  {
    title: "GitHub",
    animation: github,
    detail: [
      t("ripomanger"),
      t("Collaborating"),
      t("Project"),
      t("Documentation"),
      t("Permissions"),
      t("Automation"),
      t("Releases"),
      t("Pages"),
      t("APIse"),
    ],
  },

  {
    title: "Tailwind",
    logo: true,
    detail: [
      t("Utility"),
      t("Customization"),
      t("Design"),
      t("States"),
      t("Typography"),
      t("Flexbo"),
      t("Animati"),
      t("Production"),
    ],
  },
  {
    title: "Sass",
    logo: true,
    detail: [
      t("Variablesf"),
      t("Nesting"),
      t("Mixins"),
      t("Inheritan"),
      t("Functi"),
      t("Conditionals"),
      t("File"),
      t("Imports"),
      t("Integration"),
      t("Compilers"),
      t("dules"),
    ],
  },
  {
    title: "Ajax",
    logo: true,
    detail: [
      t("XMLHttpRequest"),
      t("Requests"),
      t("Handling"),
      t("JSON"),
      t("rror"),
      t("Asynchronous"),
      t("Sending"),
      t("imizing"),
      t("REST"),
      t("quests"),
      t("romises"),
      t("Queryd"),
      t("with"),
      t("Single"),
    ],
  },
];

export default data;
