import react from "@/lottie/react.json";
import html from "@/lottie/html.json";
import github from "@/lottie/github.json";
import javaScripts from "@/lottie/javaScripts.json";
import git from "@/lottie/git.json";

const data = (t) => [
  {
    title: "Html",
    animation: html,
    detail: [
      t("HTML5"),
      t("Attributes"),
      t("Semantic"),
      t("Forms"),
      t("Multimedia"),
      t("Graphics"),
      t("Tables"),
      t("link"),
      t("list"),
      t("Frames"),
      t("APIs"),
    ],
  },
  {
    title: "Css",
    logo: true,
    detail: [
      t("Responsive"),
      t("Media"),
      t("Selectors"),
      t("Box"),
      t("Typography"),
      t("Flexbox"),
      t("Grid"),
      t("Positioning"),
      t("Pseudo"),
      t("Variables"),
    ],
  },
  {
    title: "JavaScripts",
    animation: javaScripts,
    detail: [
      t("ES"),
      t("Type"),
      t("Operators"),
      t("Conditional"),
      t("data"),
      t("Dom"),
      t("Bom"),
      t("Acynchronous"),
      t("Error"),
    ],
  },
  {
    title: "React js",
    animation: react,
    detail: [
      t("Jsx"),
      t("class"),
      t("Based"),
      t("Functional"),
      t("LifeCycle"),
      t("hook"),
      t("Context"),
      t("api"),
      t("Validation"),
      t("Prop"),
      t("Material"),
      t("style"),
      t("Module"),
      t("Redux"),
      t("Router"),
      t("Query"),
      t("Devtools"),
    ],
  },
  {
    title: "Next",
    logo: true,
    detail: [
      "Page Router",
      "App Router",
      "Api Route Handler",
      "Next Auth",
      "Layout",
      "SSR",
      "SSG",
      "ISR",
      "Middleware",
    ],
  },
  {
    title: "TypeScript",
    logo: true,
    detail: [
      "Types",
      "Basic Types",
      "Complex Types",
      "Interfaces",
      "Classes & Object-Oriented Programming",
      "Enums",
      "Generics",
      "Functions & Type Annotations",
      "Modules & Import/Export",
      "Null, Undefined, & Optional Types",
      "Compilation Tools",
      "Debugging & Testing",
      "Type Union & Intersection",
      ,
      "Error Handling",
      "Integration with Frameworks (React, Angular, etc.)",
    ],
  },
  {
    title: "Git",
    animation: git,
    detail: [
      "Repositories",
      "Changes",
      "Branches",
      "Remote Repositories",
      "Conflicts",
      "Undo Changes",
      "Tags",
    ],
  },

  {
    title: "GitHub",
    animation: github,
    detail: [
      "Repositories Management",
      "Collaborating on GitHub",
      "Project Management Tools",
      "Documentation",
      " Security and Permissions",
      " GitHub Actions and Automation",
      " Versioning and Releases",
      " GitHub Pages",
      "Integrations and APIs",
    ],
  },

  {
    title: "Tailwind",
    logo: true,
    detail: [
      "Utility-First Classes",
      "Customization",
      "Responsive Design",
      "States - Hover, Focus, etc",
      "Typography",
      "Flexbox & Grid",
      "Animations & Transitions",
      "Production Optimization",
      "Plugins",
    ],
  },
  {
    title: "Sass",
    logo: true,
    detail: [
      "Variables",
      "Nesting",
      "Mixins & Includes",
      "Inheritance",
      "Functions",
      "Conditionals & Loops",
      "File Organization",
      "Imports",
      "Integration with Modern Workflows",
      "Compilers",
      "Modules",
    ],
  },
  {
    title: "Ajax",
    logo: true,
    detail: [
      "XMLHttpRequest",
      "GET & POST Requests",
      "Response Handling",
      "Data Formats (JSON, XML, etc.)",
      "Error Handling",
      "Asynchronous Requests",
      "Sending Data to Server",
      "Optimizing Requests",
      "Working with REST APIs",
      "Cross-Origin Requests (CORS)",
      "Promises in AJAX",
      "AJAX with jQuery",
      "Comparison with Fetch API",
      "Usage in Single Page Applications (SPA)",
    ],
  },
];

export default data;
