import type { Metadata } from "next";
import "../globals.css";
import Layout from "@/components/layout/Layout";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

const RootLayout: React.FC<LayoutProps> = async ({ children, params }) => {
  const { locale } = await params;
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={`bg-gray-900 antialiased`}>
        <NextIntlClientProvider messages={messages}>
          {" "}
          <Layout locale={JSON.parse(JSON.stringify(locale))}>
            {children}
          </Layout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};
export default RootLayout;
